/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./public/index.html"
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Design System Colors from UI specs
        'inverse-on-surface': '#eff1f4',
        'surface': '#f7f9fc',
        'surface-bright': '#f7f9fc',
        'tertiary-fixed-dim': '#e0c1a0',
        'tertiary-fixed': '#feddba',
        'on-error-container': '#93000a',
        'outline-variant': '#c4c6cc',
        'background': '#f7f9fc',
        'surface-tint': '#525f71',
        'on-tertiary-fixed': '#281804',
        'on-surface': '#191c1e',
        'on-error': '#ffffff',
        'primary-container': '#0f1c2c',
        'on-primary-container': '#778598',
        'secondary': '#755b00',
        'error': '#ba1a1a',
        'on-primary-fixed-variant': '#3a4859',
        'on-secondary-fixed': '#241a00',
        'surface-dim': '#d8dadd',
        'on-tertiary-container': '#9a7f61',
        'on-secondary-fixed-variant': '#584400',
        'secondary-fixed-dim': '#e6c364',
        'on-surface-variant': '#44474c',
        'on-tertiary-fixed-variant': '#584329',
        'secondary-container': '#fed977',
        'inverse-primary': '#bac8dc',
        'surface-container': '#eceef1',
        'surface-container-low': '#f2f4f7',
        'on-secondary-container': '#785d00',
        'primary': '#000000',
        'inverse-surface': '#2d3133',
        'on-primary-fixed': '#0f1c2c',
        'secondary-fixed': '#ffe08f',
        'tertiary-container': '#281804',
        'primary-fixed': '#d6e4f9',
        'error-container': '#ffdad6',
        'surface-container-high': '#e6e8eb',
        'surface-container-lowest': '#ffffff',
        'primary-fixed-dim': '#bac8dc',
        'on-secondary': '#ffffff',
        'on-primary': '#ffffff',
        'surface-container-highest': '#e0e3e6',
        'surface-variant': '#e0e3e6',
        'outline': '#74777d',
        'on-tertiary': '#ffffff',
        'on-background': '#191c1e',
        'tertiary': '#000000',
      },
      fontFamily: {
        'headline': ['Manrope', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Inter', 'sans-serif'],
        'display': ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
      boxShadow: {
        'glow': '0 0 20px rgba(117, 91, 0, 0.2)', // Adjusted for secondary color
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
